name: All in one file to demo artifacts, O/P and deps
on: workflow_dispatch

jobs:
  caching-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Caching deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-key-${{hashFiles('/**package-lock.json')}}

      - name: Installing deps
        run: npm ci

  artifacts-demo:
    runs-on: ubuntu-latest
    needs: caching-demo
    outputs:
      script-file: ${{steps.publish.outputs.name}}
    steps:
      - name: Checking out code
        uses: actions/checkout@v3

      - name: Installing deps
        run: npm ci
      
      - name: running tests
        run: npm run test
      
      - name: Building app
        run: npm run build

      - name: getting filename
        id: publish
        run: |
          find dist/assets/*json -type f -execdir echo 'name={}' >> $GITHUB_OUTPUT ';'
      
      - name: Artifact Build with actions
        uses: actions/upload-artifact@v3
        with:
          name: arti-name
          path: |
            dist
            index.html

      - name: Deploying
        run: echo "Deploying ....."

  output-demo:
    runs-on: ubuntu-latest
    needs: artifacts-demo
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      
      - name: Installing deps
        run: npm ci
            
      - name: running tests
        run: npm run test
            
      - name: Building app
        run: npm run build
            
      - name: Artifact Build with actions
        uses: actions/download-artifact@v3
        with:
          name: arti-name

      - name: Printing file name
        run: echo '${{needs.artifacts-demo.outputs.script-file}}'
      
      - name: Deploying
        run : echo "Deploying ....."